/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as ProfilePublicProfileIdRouteImport } from './routes/profile.$publicProfileId'
import { Route as GamesSlugRouteImport } from './routes/games/$slug'
import { Route as GamesSlugIndexRouteImport } from './routes/games/$slug/index'
import { Route as GamesSlugRelatedRouteImport } from './routes/games/$slug/related'
import { Route as GamesSlugOverviewRouteImport } from './routes/games/$slug/overview'
import { Route as GamesSlugCommunityRouteImport } from './routes/games/$slug/community'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePublicProfileIdRoute = ProfilePublicProfileIdRouteImport.update({
  id: '/$publicProfileId',
  path: '/$publicProfileId',
  getParentRoute: () => ProfileRoute,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugIndexRoute = GamesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesSlugRoute,
} as any)
const GamesSlugRelatedRoute = GamesSlugRelatedRouteImport.update({
  id: '/related',
  path: '/related',
  getParentRoute: () => GamesSlugRoute,
} as any)
const GamesSlugOverviewRoute = GamesSlugOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => GamesSlugRoute,
} as any)
const GamesSlugCommunityRoute = GamesSlugCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => GamesSlugRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/games/$slug': typeof GamesSlugRouteWithChildren
  '/profile/$publicProfileId': typeof ProfilePublicProfileIdRoute
  '/games/': typeof GamesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/$slug/community': typeof GamesSlugCommunityRoute
  '/games/$slug/overview': typeof GamesSlugOverviewRoute
  '/games/$slug/related': typeof GamesSlugRelatedRoute
  '/games/$slug/': typeof GamesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/profile/$publicProfileId': typeof ProfilePublicProfileIdRoute
  '/games': typeof GamesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/$slug/community': typeof GamesSlugCommunityRoute
  '/games/$slug/overview': typeof GamesSlugOverviewRoute
  '/games/$slug/related': typeof GamesSlugRelatedRoute
  '/games/$slug': typeof GamesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/games/$slug': typeof GamesSlugRouteWithChildren
  '/profile/$publicProfileId': typeof ProfilePublicProfileIdRoute
  '/games/': typeof GamesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/$slug/community': typeof GamesSlugCommunityRoute
  '/games/$slug/overview': typeof GamesSlugOverviewRoute
  '/games/$slug/related': typeof GamesSlugRelatedRoute
  '/games/$slug/': typeof GamesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/sign-in'
    | '/games/$slug'
    | '/profile/$publicProfileId'
    | '/games/'
    | '/profile/'
    | '/api/auth/$'
    | '/games/$slug/community'
    | '/games/$slug/overview'
    | '/games/$slug/related'
    | '/games/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/profile/$publicProfileId'
    | '/games'
    | '/profile'
    | '/api/auth/$'
    | '/games/$slug/community'
    | '/games/$slug/overview'
    | '/games/$slug/related'
    | '/games/$slug'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/sign-in'
    | '/games/$slug'
    | '/profile/$publicProfileId'
    | '/games/'
    | '/profile/'
    | '/api/auth/$'
    | '/games/$slug/community'
    | '/games/$slug/overview'
    | '/games/$slug/related'
    | '/games/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SignInRoute: typeof SignInRoute
  GamesSlugRoute: typeof GamesSlugRouteWithChildren
  GamesIndexRoute: typeof GamesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$publicProfileId': {
      id: '/profile/$publicProfileId'
      path: '/$publicProfileId'
      fullPath: '/profile/$publicProfileId'
      preLoaderRoute: typeof ProfilePublicProfileIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug/': {
      id: '/games/$slug/'
      path: '/'
      fullPath: '/games/$slug/'
      preLoaderRoute: typeof GamesSlugIndexRouteImport
      parentRoute: typeof GamesSlugRoute
    }
    '/games/$slug/related': {
      id: '/games/$slug/related'
      path: '/related'
      fullPath: '/games/$slug/related'
      preLoaderRoute: typeof GamesSlugRelatedRouteImport
      parentRoute: typeof GamesSlugRoute
    }
    '/games/$slug/overview': {
      id: '/games/$slug/overview'
      path: '/overview'
      fullPath: '/games/$slug/overview'
      preLoaderRoute: typeof GamesSlugOverviewRouteImport
      parentRoute: typeof GamesSlugRoute
    }
    '/games/$slug/community': {
      id: '/games/$slug/community'
      path: '/community'
      fullPath: '/games/$slug/community'
      preLoaderRoute: typeof GamesSlugCommunityRouteImport
      parentRoute: typeof GamesSlugRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfilePublicProfileIdRoute: typeof ProfilePublicProfileIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfilePublicProfileIdRoute: ProfilePublicProfileIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface GamesSlugRouteChildren {
  GamesSlugCommunityRoute: typeof GamesSlugCommunityRoute
  GamesSlugOverviewRoute: typeof GamesSlugOverviewRoute
  GamesSlugRelatedRoute: typeof GamesSlugRelatedRoute
  GamesSlugIndexRoute: typeof GamesSlugIndexRoute
}

const GamesSlugRouteChildren: GamesSlugRouteChildren = {
  GamesSlugCommunityRoute: GamesSlugCommunityRoute,
  GamesSlugOverviewRoute: GamesSlugOverviewRoute,
  GamesSlugRelatedRoute: GamesSlugRelatedRoute,
  GamesSlugIndexRoute: GamesSlugIndexRoute,
}

const GamesSlugRouteWithChildren = GamesSlugRoute._addFileChildren(
  GamesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SignInRoute: SignInRoute,
  GamesSlugRoute: GamesSlugRouteWithChildren,
  GamesIndexRoute: GamesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
