/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesSlugRouteImport } from './routes/games/$slug'
import { Route as GamesSlugIndexRouteImport } from './routes/games/$slug/index'
import { Route as GamesSlugRelatedRouteImport } from './routes/games/$slug/related'
import { Route as GamesSlugOverviewRouteImport } from './routes/games/$slug/overview'
import { Route as GamesSlugCommunityRouteImport } from './routes/games/$slug/community'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugIndexRoute = GamesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesSlugRoute,
} as any)
const GamesSlugRelatedRoute = GamesSlugRelatedRouteImport.update({
  id: '/related',
  path: '/related',
  getParentRoute: () => GamesSlugRoute,
} as any)
const GamesSlugOverviewRoute = GamesSlugOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => GamesSlugRoute,
} as any)
const GamesSlugCommunityRoute = GamesSlugCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => GamesSlugRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/games/$slug': typeof GamesSlugRouteWithChildren
  '/games/': typeof GamesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/$slug/community': typeof GamesSlugCommunityRoute
  '/games/$slug/overview': typeof GamesSlugOverviewRoute
  '/games/$slug/related': typeof GamesSlugRelatedRoute
  '/games/$slug/': typeof GamesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/games': typeof GamesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/$slug/community': typeof GamesSlugCommunityRoute
  '/games/$slug/overview': typeof GamesSlugOverviewRoute
  '/games/$slug/related': typeof GamesSlugRelatedRoute
  '/games/$slug': typeof GamesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/games/$slug': typeof GamesSlugRouteWithChildren
  '/games/': typeof GamesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/games/$slug/community': typeof GamesSlugCommunityRoute
  '/games/$slug/overview': typeof GamesSlugOverviewRoute
  '/games/$slug/related': typeof GamesSlugRelatedRoute
  '/games/$slug/': typeof GamesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/games/$slug'
    | '/games/'
    | '/api/auth/$'
    | '/games/$slug/community'
    | '/games/$slug/overview'
    | '/games/$slug/related'
    | '/games/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/games'
    | '/api/auth/$'
    | '/games/$slug/community'
    | '/games/$slug/overview'
    | '/games/$slug/related'
    | '/games/$slug'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/games/$slug'
    | '/games/'
    | '/api/auth/$'
    | '/games/$slug/community'
    | '/games/$slug/overview'
    | '/games/$slug/related'
    | '/games/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  GamesSlugRoute: typeof GamesSlugRouteWithChildren
  GamesIndexRoute: typeof GamesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug/': {
      id: '/games/$slug/'
      path: '/'
      fullPath: '/games/$slug/'
      preLoaderRoute: typeof GamesSlugIndexRouteImport
      parentRoute: typeof GamesSlugRoute
    }
    '/games/$slug/related': {
      id: '/games/$slug/related'
      path: '/related'
      fullPath: '/games/$slug/related'
      preLoaderRoute: typeof GamesSlugRelatedRouteImport
      parentRoute: typeof GamesSlugRoute
    }
    '/games/$slug/overview': {
      id: '/games/$slug/overview'
      path: '/overview'
      fullPath: '/games/$slug/overview'
      preLoaderRoute: typeof GamesSlugOverviewRouteImport
      parentRoute: typeof GamesSlugRoute
    }
    '/games/$slug/community': {
      id: '/games/$slug/community'
      path: '/community'
      fullPath: '/games/$slug/community'
      preLoaderRoute: typeof GamesSlugCommunityRouteImport
      parentRoute: typeof GamesSlugRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GamesSlugRouteChildren {
  GamesSlugCommunityRoute: typeof GamesSlugCommunityRoute
  GamesSlugOverviewRoute: typeof GamesSlugOverviewRoute
  GamesSlugRelatedRoute: typeof GamesSlugRelatedRoute
  GamesSlugIndexRoute: typeof GamesSlugIndexRoute
}

const GamesSlugRouteChildren: GamesSlugRouteChildren = {
  GamesSlugCommunityRoute: GamesSlugCommunityRoute,
  GamesSlugOverviewRoute: GamesSlugOverviewRoute,
  GamesSlugRelatedRoute: GamesSlugRelatedRoute,
  GamesSlugIndexRoute: GamesSlugIndexRoute,
}

const GamesSlugRouteWithChildren = GamesSlugRoute._addFileChildren(
  GamesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  GamesSlugRoute: GamesSlugRouteWithChildren,
  GamesIndexRoute: GamesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
